config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :milestones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  mount_uploaders :childhood_images, ChildhoodImagesUploader
  mount_uploader :adolescence_image, AdolescenceImageUploader
  mount_uploader :adulthood_image, AdulthoodImageUploader
  mount_uploader :mature_age_image, MatureAgeImageUploader

  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :childhood_content, presence: true, length: { maximum: 65_535 }
  validates :adulthood_content, presence: true, length: { maximum: 65_535 }
  validates :mature_age_content, presence: true, length: { maximum: 65_535 }

  enum status: { published: 0, draft: 1,  unpublished: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :milestones

  validates :name, presence: true, length: { maximum: 25 }
  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def mine?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  add_flash_types :success, :info
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("users.create.success")
    else
      flash.now[:info] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController

  def index
    @milestones = Milestone.includes(:user).order(updated_at: :desc)
  end

  def new
    @milestone = Milestone.new
  end

  def create
    @milestone = current_user.milestones.build(milestone_params)
    if @milestone.save
      redirect_to milestones_path, success: t("milestones.create.success")
    else
      flash.now[:info] = t("milestones.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @milestone = Milestone.find(params[:id])
  end

  def edit
    @milestone = current_user.milestones.find(params[:id])
  end

  def update
    @milestone = current_user.milestones.find(params[:id])
    if @milestone.update(milestone_params)
      redirect_to milestone_path(@milestone), success: t("milestones.update.success")
    else

      flash.now[:info] = t("milestones.update.failure")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @milestone = current_user.milestones.find(params[:id])
    @milestone.destroy!
    redirect_to milestones_path, success: t("milestones.delete.success"), status: :see_other
  end

  private

  def milestone_params
    params.require(:milestone).permit(:title, :status, :childhood_content, :adulthood_content, :mature_age_content, :adolescence_image, :adolescence_image_cache, :adulthood_image, :adulthood_image_cache, :mature_age_image, :mature_age_image_cache, { childhood_images: [] }, :childhood_images_cache)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # skip_before_action :require_login
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to milestones_path, success: t("user_sessions.create.success")
    else
      flash.now[:info] = t("user_sessions.create.failure")
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t("user_sessions.destroy.success")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to milestones_path, success: t("users.create.success")
    else
      flash.now[:info] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Timeline" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favi.ico') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/gh/dixonandmoe/rellax@master/rellax.min.js"></script>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FGYQ4M14G2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-FGYQ4M14G2');
    </script>
  </head>

  <body class="bg-slate-400">
    <%= render "shared/flash_message" %>

    <div class="fixed top-5 right-5 z-50">
      <button onclick="toggleMenu()" class="bg-gray-800 text-white rounded-full w-12 h-12 text-2xl hover:bg-gray-700">
        <i class="ri-menu-line"></i>
      </button>
    </div>

    <div id="menu" class="fixed top-16 right-5 bg-white border border-gray-300 rounded-lg shadow-lg z-40 hidden">
      <ul class="p-2">
        <li class="py-1"><%= link_to root_path do %>ホーム<% end %></li>
        <li class="py-1"><%= link_to milestones_path do %>年表リスト<% end %></li>
        <% if logged_in? %>
          <li class="py-1"><%= link_to new_milestone_path, data: { turbo: false } do %>年表作成<% end %></li>
          <li class="py-1"><%= link_to logout_path, data: { turbo_method: :delete } do %>ログアウト<% end %></li>
        <% else %>
          <li class="py-1"><%= link_to login_path do %>ログイン<% end %></li>
        <% end %>
      </ul>
    </div>

    <%= yield %>
  </body>

  <script>
    function toggleMenu() {
      const menu = document.getElementById("menu");
      menu.classList.toggle("hidden");
    }

    function showModal() {
      document.getElementById('modal').showModal();
    }

    function closeModal() {
      document.getElementById('modal').close();
    }

  </script>

</html>

app/views/milestones/_form.html.erb
<div class="container mx-auto">
  <div class="flex justify-center w-full">
    <div class="w-2/3 max-w-[400px]">

      <%= form_with model: milestone do |f| %>
        <div class="my-6 font-noto font-light w-full">
          <%= f.label :title, class: "text-md font-light" %>
          <%= f.text_field :title, class: "border p-1 rounded-sm w-full" %>
          <%= render 'shared/error_message_for_field', object: f.object, attribute: :title %>
        </div>

        <div class="mb-6 font-noto font-light">
          <%= f.label :childhood_content, class: "text-md" %>
          <%= f.text_area :childhood_content, class: 'border rounded-md p-2 h-24 w-full', placeholder: "例：幼年期" %>
          <%= render 'shared/error_message_for_field', object: f.object, attribute: :childhood_content %>
        </div>

        <div class="mb-6 font-noto font-light">
          <%= f.label :adulthood_content, class: "text-md" %>
          <%= f.text_area :adulthood_content, class: 'border rounded-md p-2 h-24 w-full', placeholder: "例：青年期" %>
          <%= render 'shared/error_message_for_field', object: f.object, attribute: :adulthood_content %>
        </div>

        <div class="mb-10 font-noto font-light">
          <%= f.label :mature_age_content, class: "text-md" %>
          <%= f.text_area :mature_age_content, class: 'border rounded-md p-2 h-24 w-full', placeholder: "例：成人後" %>
          <%= render 'shared/error_message_for_field', object: f.object, attribute: :mature_age_content %>
        </div>

        <p class="mb-4 font-noto text-red-500 text-sm">※以下写真は任意です</p>

        <div class="mb-6 font-noto">
          <%= f.label "複数画像可：", class: "text-md font-light" %>
          <label>
            <span class="py-1 px-2 text-sm font-noto font-thin text-white bg-transparent border border-white rounded cursor-pointer hover:text-gray-400 hover:bg-gray-200 hover:border-transparent">ファイルを選択</span>
            <%= f.file_field :childhood_images, multiple: true, include_hidden: false, class: 'hidden', id: 'childhood_images' %>
          </label>

          <div id="previews" class="flex flex-col items-center">
            <% if @milestone.childhood_images.present? %>
              <% @milestone.childhood_images.each do |image| %>
                <%= image_tag(image.url, class: 'preview-image max-h-52 mt-3 ') %>
              <% end %>
            <% else %>
              <%= image_tag('noise.jpg', class: 'preview-image max-h-52 mt-3 ') %>
            <% end %>
          </div>
          <%= f.hidden_field :childhood_images_cache %>
        </div>


        <div class="mb-6 font-noto">
          <%= f.label "画像１：", class: "text-md font-light" %>
          <label>
            <span class="py-1 px-2 text-sm font-noto font-thin text-white bg-transparent border border-white rounded cursor-pointer hover:text-gray-400 hover:bg-gray-200 hover:border-transparent">ファイルを選択</span>
            <%= f.file_field :adolescence_image, class: 'hidden', id: 'adolescence_image' %>
          </label>

          <div class="flex items-center justify-center">
            <%= image_tag(@milestone.adolescence_image.url, class: 'max-h-52 mt-3', id: 'first_preview') %>
          </div>
          <%= f.hidden_field :adolescence_image_cache %>
        </div>


        <div class="mb-6 font-noto">
          <%= f.label "画像２：", class: "text-md font-light" %>
          <label>
            <span class="py-1 px-2 text-sm font-noto font-thin text-white bg-transparent border border-white rounded cursor-pointer hover:text-gray-400 hover:bg-gray-200 hover:border-transparent">ファイルを選択</span>
            <%= f.file_field :adulthood_image, class: 'hidden', id: 'adulthood_image' %>
          </label>

          <div class="flex items-center justify-center">
            <%= image_tag(@milestone.adulthood_image.url, class: 'max-h-52 mt-3', id: 'second_preview') %>
          </div>
          <%= f.hidden_field :adulthood_image_cache %>
        </div>

        <div class="mb-6 font-noto">
          <%= f.label "画像３：", class: "text-md font-light" %>
          <label>
            <span class="py-1 px-2 text-sm font-noto font-thin text-white bg-transparent border border-white rounded cursor-pointer hover:text-gray-400 hover:bg-gray-200 hover:border-transparent">ファイルを選択</span>
            <%= f.file_field :mature_age_image, class: 'hidden', id: 'mature_age_image' %>
          </label>

          <div class="flex items-center justify-center">
            <%= image_tag(@milestone.mature_age_image.url, class: 'max-h-52 mt-3', id: 'third_preview') %>
          </div>
          <%= f.hidden_field :mature_age_image_cache %>
        </div>



        <div class="text-center mb-6 sm:mb-10">
          <%= f.submit t('helpers.submit.submit'), class: "border border-slate-600 bg-slate-600 text-white w-1/4 font-thin cursor-pointer hover:text-black hover:bg-white hover:shadow-lg transition duration-200" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/milestones/_milestone.html.erb
<div id="<%= dom_id(milestone) %>">
  <div class="flex flex-col h-20 p-3 border border-black/50 rounded-md bg-slate-300 overflow-hidden transition duration-500 hover:shadow-2xl hover:bg-white">
    <%= link_to milestone_path(milestone), data: { turbo: false }, class: "w-full max-w-[82%]" do %>
      <div class="flex items-end justify-between mt-1 ml-1">
        <div>
          <div class="text-xs"><%= milestone.user.name %></div>
          <div class="pt-1 text-lg line-clamp-1"><%= milestone.title %></div>
        </div>
        <% if current_user&.mine?(milestone) %>
        <div class="flex space-x-1">

          <%= link_to edit_milestone_path(milestone), title: "編集" do %>
            <i class="ri-edit-box-line text-xl text-blue-500 outline-none"></i>
          <% end %>

          <button onclick="showModal()" class="outline-none hover:animate-quake">
            <i class="ri-delete-bin-5-line text-xl text-red-400"></i>
          </button>
          <dialog id="modal" class="rounded-lg p-8 bg-white shadow-lg w-96">

            <p class="text-center text-lg font-medium">投稿を削除しますか？</p>
            <div class="flex justify-between ml-10 mr-14 mt-4">

              <button onclick="closeModal()" class="btn btn-outline outline-none font-thin text-xs md:text-base">キャンセル</button>

              <%= link_to "削除", milestone_path(milestone), class: "btn btn-outline font-thin text-xs text-red-400 md:text-base", data: { turbo_method: :delete } %>
            </div>

          </dialog>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/milestones/edit.html.erb
<%= render 'form', milestone: @milestone %>

app/views/milestones/index.html.erb
<div class="container h-screen mx-auto">
  <div class="pt-20 space-y-10">
    <div class="flex items-center justify-center w-full">
      <%= link_to t("milestones.new.title"), new_milestone_path, class: "w-1/4 flex justify-center cursor-pointer text-base font-thin text-white border border-black/50 bg-black/50 hover:text-black hover:bg-white hover:shadow-lg transition duration-200 outline-none" %>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8 mx-4">
        <% if @milestones.present? %>
          <%= render @milestones %>
        <% else %>
          <p class="mb-3 mt-4">年表がありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/milestones/new.html.erb
<meta name="turbo-cache-control" content="no-cache">

<%= render 'form', milestone: @milestone %>

app/views/milestones/show.html.erb
<meta name="turbo-cache-control" content="no-cache">
<meta name="turbo-visit-control" content="reload">

<div class="horizontalWrapper relative h-screen p-8 overflow-y-hidden sm:overflow-y-visible">
  <ul class="horizontals absolute top-0 left-0 flex h-full overflow-y-hidden md:min-h-[670px]">
    <li id="opening" class="flex items-center justify-center min-w-screen h-full px-8 bg-gray-400 text-white">
      <h1 class="text-5xl mx-20 font-noto font-thin max-w-[80%]"><%= @milestone.title %>の年表</h1>
      <div class="min-w-20"><%= image_tag('path.png') %></div>
    </li>

    <li id="divide" class="min-w-fit">
      <%= image_tag('divide.png', class: 'h-full size-fit') %>
    </li>

    <li id="childhood" class="relative min-w-[1000px] md:min-w-[1300px] flex text-white bg-[#87CEEB]">

      <div class="w-5/12 absolute top-32 left-32 pr-16 bg-[#0756CE] border-2 border-white shadow-custom-shadow">
        <div class="textarea w-full py-4 pl-4 text-base break-words font-noto font-light z-10">
          <%= simple_format(@milestone.childhood_content, class: "line-clamp-15 leading-loose") %>
        </div>
      </div>

      <div class="absolute bottom-0 left-20 sm:left-0">
        <%= image_tag('people.png', class: "people h-64 z-50") %>
      </div>

      <div class="absolute top-0 right-32">
        <%= image_tag('ponyo.png', class: "ponyo h-20 z-50") %>
      </div>

      <div id="slider" class="flex absolute top-[35%] right-32 aspect-video w-[349px] md:w-[549px] bg-white border-8 border-white overflow-hidden shadow-custom-wide-shadow z-10">
        <% if @milestone.childhood_images.present? %>
          <% @milestone.childhood_images.each do |image| %>
            <div class="slide min-w-fit z-10">
              <img src="<%= image.url %>" class="aspect-video w-[349px] md:w-[549px]">
            </div>
          <% end %>
        <% else %>
          <div class="w-full">
            <%= image_tag('noise.jpg', class: "w-full h-full") %>
          </div>
        <% end %>
      </div>

    </li>


    <li id="adulthood" class="spikes relative min-w-[1000px] md:min-w-[1300px] text-black bg-[#F4A15A]">
      <div class="relative mx-auto w-11/12 h-screen mt-10">
        <div class="absolute top-[12%] left-20">
          <%= image_tag('board.png', class: "aspect-video min-w-[800px] md:min-w-[1000px] shadow-xl") %>
        </div>
        <div class="w-2/5 md:w-1/3 absolute top-[17%] left-24">
          <div class="textarea w-full pl-4 pr-10 md:pr-0 text-base break-words font-noto font-light z-10">
            <%= simple_format(@milestone.adulthood_content, class: "line-clamp-14 leading-loose") %>
          </div>
        </div>

        <div class="flex flex-col absolute top-[18%] right-24 md:right-44 space-y-10 mt-2">
          <div class="mx-auto aspect-square w-[170px] md:w-[210px] bg-white border border-dashed rounded-full border-black/50 z-10">
            <%= image_tag(@milestone.adolescence_image.url, class: "aspect-square w-[170px] md:w-[210px] rounded-full") %>
          </div>

          <div class="aspect-video w-[250px] md:w-[350px] bg-white border border-dashed border-black/50 z-10">
            <%= image_tag(@milestone.adulthood_image.url, class: "aspect-video w-[250px] md:w-[350px]") %>
          </div>

          <div class="absolute -top-[24%] md:-top-[19%] right-[34%] md:right-[38%] transform rotate-[20deg] z-50">
            <%= image_tag('tape2.png', class: "h-20") %>
          </div>
          <div class="absolute bottom-[26%] md:bottom-[33%] -right-[13%] md:-right-[8%] transform rotate-45 z-50">
            <%= image_tag('tape.png', class: "h-20") %>
          </div>
          <div class="absolute -bottom-[8%] md:-bottom-[6%] -left-[12%] md:-left-[8%] transform rotate-45 z-50">
            <%= image_tag('tape.png', class: "h-20") %>
          </div>

        </div>
      </div>

      <div class="absolute top-0 right-24 md:right-32">
        <%= image_tag('spider.png', class: "spider h-60 z-50") %>
      </div>

    </li>

    <li id="mature_age" class="spikes min-w-screen text-white relative flex items-center justify-center bg-[#2B2762]">
      <div class="flex flex-col w-5/6 space-y-20 md:space-y-14">
        <div class="mx-auto justify-center aspect-video w-5/6 min-w-[300px] md:min-w-[400px] max-w-[650px] bg-black border border-black/50 z-10">
          <%= image_tag(@milestone.mature_age_image.url, class: "w-full aspect-video min-w-[300px] md:min-w-[400px]] max-w-[650px]") %>
        </div>

        <div class="textarea w-full max-w-[900px] mx-auto border rounded-sm p-4 text-base leading-tight break-words font-noto font-light">
          <%= simple_format(@milestone.mature_age_content, class: "line-clamp-6 leading-loose mx-4") %>
        </div>
      </div>

      <div class="absolute top-[10%] md:top-[5%] left-[4%]">
        <%= image_tag('ghost.png', class: "h-20 z-50") %>
      </div>

      <div class="absolute bottom-24 md:bottom-10 right-2 md:right-[5%]">
        <%= image_tag('teresa.png', class: "h-20 z-50") %>
      </div>

    </li>

  </ul>
</div>

app/views/shared/_error_message_for_field.html.erb
<% if object.errors[attribute].present? %>
  <p class="text-red-500 text-xs md:text-sm mt-1">
    <%= object.errors.full_messages_for(attribute).join(', ') %>
  </p>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert-<%= message_type %> fixed flex items-center w-full h-8 pl-4 text-white bg-black/50 animate-flash z-20">
    <%= message %>
  </div>
<% end %>

app/views/static_pages/top.html.erb
<div class="container h-screen mx-auto" >
  <div class="flex flex-col h-full w-full justify-center space-y-14 pb-20">
    <div class="mx-auto">
      <p class="text-7xl text-white font-noto font-thin">私の年表</p>
    </div>
    <% if logged_in? %>
      <div class="flex justify-center text-lg font-noto font-thin"><%= current_user.name %> 様</div>
    <% else %>
      <div class="flex justify-center space-x-4">
        <%= link_to t("static_pages.top.sign_up"), new_user_path, class: "w-1/4 flex justify-center cursor-pointer text-sm sm:text-base font-thin text-white border border-slate-600 bg-slate-600 hover:text-black hover:bg-white hover:shadow-lg transition duration-200 outline-none" %>
        <%= link_to t("static_pages.top.login"), login_path, class: "w-1/4 flex justify-center cursor-pointer text-sm sm:text-base font-thin text-white border border-slate-600 bg-slate-600 hover:text-black hover:bg-white hover:shadow-lg transition duration-200 outline-none" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container h-screen mx-auto" >
  <div class="h-full flex items-center justify-center pb-8">
    <%= form_with url: login_path do |f| %>
      <div>
        <%= f.label :email, t(".email"), class: "text-sm" %>
        <%= f.text_field :email, class: "w-full border-b border-black/50 bg-transparent rounded-none outline-none" %>
      </div>

      <div class="my-8">
        <%= f.label :password, t(".password"), class: "text-sm" %>
        <%= f.text_field :password, class: "w-full border-b border-black/50 bg-transparent rounded-none outline-none" %>
      </div>

      <div class="text-center pt-4">
        <%= f.submit t('.login'), class: "w-1/4 cursor-pointer font-thin text-white border border-slate-600 bg-slate-600 hover:text-black hover:bg-white hover:shadow-lg transition duration-200" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id(user) %>">
  <div class="group flex flex-col h-20 p-3 border border-black/50 rounded-md overflow-hidden transition duration-500 hover:shadow-2xl hover:bg-white">
    <div class="flex flex-col items-center">
      <div class="flex-grow w-full relative">
        <%= link_to user_path(user) do %>
          <div class="flex">
            <div class="relative -left-8 -top-5">
              <%= image_tag(user.avatar.url, class: 'border border-2 rounded-full size-24 group-hover:shadow-2xl grayscale group-hover:filter-none group-hover:rotate-12 transition duration-500') %>
            </div>
            <div>
              <%= user.name %>
              <div class="flex text-xs gap-2 pt-2 text-muted-foreground">
                <p>フォロー中: <%= user.followees.count %></p>
                <p>フォロワー: <%= user.followers.count %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container h-screen mx-auto" >
  <div class="h-full flex items-center justify-center">
    <%= form_with model: @user do |f| %>
      <div class="pt-6">
        <%= f.label :name, t(".name"), class: "text-sm" %>
        <%= f.text_field :name, class: "w-full border-b border-black/50 bg-transparent focus:bg-white focus:border-white focus:bg-opacity-50 focus:shadow-md transition duration-500 rounded-none outline-none" %>
        <%= render 'shared/error_message_for_field', object: f.object, attribute: :name %>
      </div>

      <div class="py-8">
        <%= f.label :email, t(".email"), class: "text-sm" %>
        <%= f.text_field :email, class: "w-full border-b border-black/50 bg-transparent focus:bg-white focus:border-white focus:bg-opacity-50 focus:shadow-md transition duration-500 rounded-none outline-none" %>
        <%= render 'shared/error_message_for_field', object: f.object, attribute: :email %>
      </div>

      <div class="pb-8">
        <%= f.label :password, t(".password"), class: "text-sm" %>
        <%= f.text_field :password, class: "w-full border-b border-black/50 bg-transparent focus:bg-white focus:border-white focus:bg-opacity-50 focus:shadow-md transition duration-500 rounded-none outline-none" %>
        <%= render 'shared/error_message_for_field', object: f.object, attribute: :password %>
      </div>

      <div class="pb-2 md:mb-8">
        <%= f.label :password_confirmation, t(".password_confirmation"), class: "text-sm" %>
        <%= f.text_field :password_confirmation, class: "w-full border-b border-black/50 bg-transparent focus:bg-white focus:border-white focus:bg-opacity-50 focus:shadow-md transition duration-500 rounded-none outline-none" %>
        <%= render 'shared/error_message_for_field', object: f.object, attribute: :password_confirmation %>
      </div>

      <div class="text-center my-4">
        <%= f.submit t('.submit'), class: "w-1/4 cursor-pointer font-thin text-white border border-slate-600 bg-slate-600 hover:text-black hover:bg-white hover:shadow-lg transition duration-200" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, t('.title')) %>

<%= render 'profiles/profile', user: @user %>